### ISSUE TITLE
The conditions for installing Docker from a binary file are not met

### ISSUE THREAD

**Issue by Uchiha-Peng** [sailfish-lavender/builds#10]
I want to install Docker on Sailfish, but I encountered two problems when checking whether the conditions are met. They may be kernel problems, can it be solved?

Generally Necessary:
* - CONFIG_VETH: missing
* - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
* - CONFIG_NETFILTER_XT_MATCH_IPVS: missing
* - CONFIG_POSIX_MQUEUE: missing

![image](https://user-images.githubusercontent.com/20633089/84497026-97f09680-ace0-11ea-9ae5-51d6d78f14b9.png)

**Comment by Danct12** [comment]
I'll look into it, and soon I'll release the last preview (which will have 3.3) before moving adapting to OBS.

**Comment by Uchiha-Peng** [comment]
Haha, thank you very much. I also look forward to your new version and visit your Twitter frequently.

**Comment by Uchiha-Peng** [comment]
> I'll look into it, and soon I'll release the last preview (which will have 3.3) before moving adapting to OBS.



> 我会研究它，很快我会发布最后一个预览（将有3.3）之前移动到适应OBS。

Being able to install Docker containers directly on a mobile phone without resorting to other applications is a cool thing, which also makes sense. I know Sailfish OS can do it, because I have read some tutorials, Redmi Note 7 is not officially supported by Jolla, I guess it may be that something is missing when porting. [Here Is Tutorial](https://birdzhang.xyz/2018/09/05/Docker-on-SailfishOS/)

**Comment by Htylol** [comment]
When will the last preview be?

**Comment by Uchiha-Peng** [comment]
> When will the last preview be?

I am also waiting for the next update

**Comment by Danct12** [comment]
Now a part of 20200630.
