### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by Htylol** [sailfish-lavender/builds#11]
How to install flatpak? The ssu repository is not available, or how can I install it?

**Comment by Danct12** [comment]
It works fine for me

**Comment by Htylol** [comment]
> It works fine for me

Thanks, figured it out. Now everything works, though only kde applications work. True gimp, libreoffice, geany, give an error during startup and do not turn on

**Comment by Danct12** [comment]
> gimp, libreoffice, geany, give an error during startup and do not turn on

not our fault, so any flatpak related issue should be reported to upstream.
