### ISSUE TITLE
harbour-containers

### ISSUE THREAD

**Issue by Htylol** [sailfish-lavender/builds#12]
Hey. Can you make harbor-containers support in the next build (if it certainly will)?

https://github.com/sailfish-containers/harbour-containers

https://youtu.be/8PnDZtKzsSc

**Comment by Htylol** [comment]
https://build.merproject.org/package/binary/home:birdzhang/harbour-containers?arch=armv8el&filename=harbour-containers-0.3%2Bmaster.20200711015541.f3ff909-1.1.1.jolla.armv7hl.rpm&repository=sailfish_latest_armv7hl

![tmp_4279](https://user-images.githubusercontent.com/55416159/87273661-2bd99c00-c4f3-11ea-92ed-88f2a75fe933.png)

**Comment by 0312birdzhang** [comment]
Kernel should be fine.
Install [lxc-templates-desktop](https://github.com/sailfish-containers/lxc-templates-desktop/releases/tag/1.1-4) and read this wiki https://github.com/sailfish-containers/lxc-templates-desktop/wiki/Usage
For GUI https://github.com/sailfish-containers/lxc-templates-desktop/wiki/Desktop

**Comment by Htylol** [comment]
![tmp_6333](https://user-images.githubusercontent.com/55416159/87831348-aa8c5b80-c89c-11ea-8c11-03f19eac3db3.png)
> Kernel should be fine.
> Install [lxc-templates-desktop](https://github.com/sailfish-containers/lxc-templates-desktop/releases/tag/1.1-4) and read this wiki https://github.com/sailfish-containers/lxc-templates-desktop/wiki/Usage
> For GUI https://github.com/sailfish-containers/lxc-templates-desktop/wiki/Desktop

not work, why?
![tmp_5759](https://user-images.githubusercontent.com/55416159/87828572-a5c4a900-c896-11ea-92bf-220734fb25cd.png)

**Comment by Htylol** [comment]
Not work, how fix this?
![tmp_3734](https://user-images.githubusercontent.com/55416159/87834787-b3812b00-c8a4-11ea-818c-3e26938e16f5.png)

**Comment by Htylol** [comment]
https://youtu.be/Pwvu5k9XtUg with virtual keyboard, https://youtu.be/Miyxfc038y8

**Comment by 0312birdzhang** [comment]
https://github.com/sailfish-lavender/android_kernel_xiaomi_lavender/blob/28d751ee4b25873c767b7f98f0dc07436b4ce3bb/arch/arm64/configs/lavender-perf_defconfig#L173 disable CONFIG_SCHED_TUNE

**Comment by Htylol** [comment]
I changed, but on which compiler to build this kernel?

**Comment by Htylol** [comment]
I used export CROSS_COMPILE=aarch64-linux-gnu-, it builds, but then errors start to appear
![IMG_20200718_143443](https://user-images.githubusercontent.com/55416159/87849739-54530300-c904-11ea-92d3-0ce69c495381.jpg)

**Comment by 0312birdzhang** [comment]
you need @Danct12 build a new

**Comment by Htylol** [comment]
I see. Thanks. And so, it would be nice if Danct12, not entirely, but at least assembled a new kernel so that lxc containers and the program itself as a whole would work stably. And then I just look, the developers of this program, during this time have already made the on-screen keyboard and change the screen orientation too.

**Comment by Htylol** [comment]
A few days ago, a new version of the program appeared
![tmp_5608](https://user-images.githubusercontent.com/55416159/87851173-b8c78f80-c90f-11ea-80c6-64c17652401a.png)
![tmp_5608](https://user-images.githubusercontent.com/55416159/87851176-bebd7080-c90f-11ea-877d-f0be469398e6.png)
![tmp_5608](https://user-images.githubusercontent.com/55416159/87851190-cbda5f80-c90f-11ea-8c57-477946fef23b.png)

**Comment by Htylol** [comment]
This linaro 4.9 2016.02
![IMG_20200718_210134](https://user-images.githubusercontent.com/55416159/87856661-e45f6f80-c939-11ea-85c2-e608e672cf35.jpg)

**Comment by Htylol** [comment]
I compiled the kernel, though it's in Image.gz-dtb, what should I do with it now? Compiler gcc 4.9.* 20150123

**Comment by FakeShell** [comment]
Please try with the new 4.5.0.16 build
