### ISSUE TITLE
Lavender and fingerprint sensor

### ISSUE THREAD

**Issue by liss21** [sailfish-lavender/builds#14]
Greetings. Installed the latest available 3.3.0.16 (Rokua) on Redmi Note 7. Installed via Orange Fox 10.1 with encryption disabled. During the initial setup, I entered the security code and tried to configure the fingerprint. The system asks to touch the sensor several times, there is a reaction to the finger and at the end reports that it is impossible to get a fingerprint. Is it possible to fix it somehow?

**Comment by FakeShell** [comment]
Please try with the new 4.5.0.16 build
