### ISSUE TITLE
Cellular data

### ISSUE THREAD

**Issue by Danct12** [sailfish-lavender/builds#2]
Same issue as https://github.com/sailfish-on-davinci/issues/issues/4

**Comment by 0312birdzhang** [comment]
Do you have `/dev/rmnet*`? And can you start `vendor.dataqti` service?

Reference: http://www.merproject.org/logs/%23sailfishos-porters/%23sailfishos-porters.2019-09-07.log.html#t2019-09-07T13:48:56

**Comment by Danct12** [comment]
@0312birdzhang

I think this can be closed now, I was able to fix it, all you need is to build [dummy_netd](https://github.com/mer-hybris/dummy_netd) and enable the service.

**Comment by 0312birdzhang** [comment]
Thank you, it's working 👍

**Comment by micheleciondolo** [comment]
> Thank you, it's working +1

Hi!! 
Tried so hard to build dummy_netd but I cant. It have unmet dependencies (libgbinder-devel).. Can you give me a suggestion? :)

**Comment by Danct12** [comment]
Fixed, now a part of [2020/04/29 preview](https://github.com/sailfish-lavender/builds/releases/tag/20200429)
