### ISSUE TITLE
Wifi 5Ghz not works

### ISSUE THREAD

**Issue by ostapyrih** [sailfish-lavender/builds#4]

**Comment by Danct12** [comment]
Can you give me `journalctl -xe` when you connect to 5GHz Wi-Fi? I don't have a access point that does 5GHz and it's not common here in Vietnam.

**Comment by ostapyrih** [comment]
It's not even display 5ghz networks

**Comment by JSPiRiT1337** [comment]
> It's not even display 5ghz networks

working fine here

**Comment by ScardracS-zz** [comment]
> > It's not even display 5ghz networks
> 
> working fine here

How it's possible?

**Comment by JSPiRiT1337** [comment]
> > > It's not even display 5ghz networks
> > 
> > 
> > working fine here
> 
> How it's possible?

I don't know but it does

**Comment by gbowsky** [comment]
works for me

**Comment by Danct12** [comment]
I'll add a invalid label for now (due to people claiming it works fine for them), will look into it at my friend's network

**Comment by ScardracS-zz** [comment]
I report the 5GHz WiFi works as expected

**Comment by Danct12** [comment]
Just tested at our friend's (@asriel-danctnix) company network. 5 GHz works perfectly fine, try upgrade your firmware or something should fix.
