### ISSUE TITLE
Wi-Fi ceases to work when dual-booting

### ISSUE THREAD

**Issue by Htylol** [sailfish-lavender/builds#6]
After installing the system, everything works for the preview build with its description, time, if the android kernel is flashed back through twrp, then android starts, but Wi-fi stops working in it. If, after the entire installation, start downloading from the android, then Wi-Fi works on the android, but sailfish after that does not start already.

**Comment by Danct12** [comment]
We have tested Android without encryption and it does not live up to our expectation. This device depends on encryption for fingerprint scanner and even for saving passwords.

So pretty much we're settled on removing Android dual-boot support.

![image](https://user-images.githubusercontent.com/19162768/80410393-b2b7a900-88f4-11ea-843b-12b4dd1951df.png)
