### ISSUE TITLE
Can anbox be installed here? 

### ISSUE THREAD

**Issue by naive17** [sailfish-lavender/builds#8]

**Comment by Danct12** [comment]
On Wednesday, May 13, 2020 4:03:44 PM +07 koso00 wrote:
> 
No, not really. Anbox is currently broken and until someone steps up to 
maintain it then we can add it.

-- 
Dreemurrs Embedded Labs (aka DanctNIX)

* Discord: https://discord.gg/AvtdRJ3
* Matrix: #danctnix-general:matrix.org

**Comment by naive17** [comment]
I tried to use the rom as a daily driver for a week but for the absence of a functional browser it's almost impossible to plan to use sfos as daily driver. everything else worked great.
So if we find a way to port and fix anbox we can stick to firefox and use it.
I tried everything i could with quicksilver and ozone-qt but i didn't get a single build running

**Comment by Danct12** [comment]
> absence of a functional browser

You can check out Webcat browser.

**Comment by Htylol** [comment]
https://build.sailfishos.org/package/show/home:birdzhang:anbox/anbox

![Screenshot-20-08-16-22-29-49](https://user-images.githubusercontent.com/55416159/90340413-78902580-e011-11ea-9d6a-b780a87cead0.png)
![Screenshot-20-08-16-22-29-43](https://user-images.githubusercontent.com/55416159/90340423-85ad1480-e011-11ea-9976-632b557adaaf.png)
![Screenshot-20-08-16-22-29-35](https://user-images.githubusercontent.com/55416159/90340446-aa08f100-e011-11ea-8f79-e08752129d62.png)
![Screenshot-20-08-16-22-29-26](https://user-images.githubusercontent.com/55416159/90340451-b0976880-e011-11ea-8045-6c8943b769b9.png)

**Comment by FakeShell** [comment]
anbox is deprecated. closing
